on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASS }}" | docker login https://ai-rebornsoft.asuscomm.com:5000 -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Docker Build and Push
        run: |
          current_time=$(date +"%Y%m%d%H%M%S")
          registry=ai-rebornsoft.asuscomm.com:5000/noorwave-admin-front
          docker buildx build -t $registry:$current_time -t $registry:latest --platform=linux/amd64 .
          docker push $registry:$current_time
          docker push $registry:latest
          docker logout

      - run: gh api /repos/reborn-soft/noorwave-server/dispatches -f event_type='deploy'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
